# Players => Layout Mapping
first_card: &first_card
  top: 180px
  left: 115px
first_player: &first_player
  top: 310px
  left: 15px
top_card: &top_card
  top: 10px
  left: 115px
top_player: &top_player
  top: -120px
  left: 15px
left_card: &left_card
  top: 95px
  left: 10px
left_player: &left_player
  top: 80px
  left: -280px
right_card: &right_card
  top: 95px
  left: 220px
right_player: &right_player
  top: 80px
  left: 310px
top_left_card: &top_left_card
  <<: *left_card
  top: 10px
top_right_card: &top_right_card
  <<: *right_card
  top: 10px
top_left_player: &top_left_player
  <<: *left_player
  top: -10px
top_right_player: &top_right_player
  <<: *right_player
  top: -10px
bottom_left_card: &bottom_left_card
  <<: *left_card
  top: 140px
bottom_right_card: &bottom_right_card
  <<: *right_card
  top: 140px
bottom_left_player: &bottom_left_player
  <<: *left_player
  top: 140px
bottom_right_player: &bottom_right_player
  <<: *right_player
  top: 140px


1:
  top_margin: 40px
  cards:
    - <<: *first_card
  players:
    - <<: *first_player
2: 
  top_margin: 100px
  cards:
    - <<: *first_card
    - <<: *top_card
  players:
    - <<: *first_player
    - <<: *top_player
3:
  top_margin: 40px
  cards:
    - <<: *first_card
    - <<: *top_left_card
    - <<: *top_right_card
  players:
    - <<: *first_player
    - <<: *top_left_player
    - <<: *top_right_player
4:
  top_margin: 100px
  cards:
    - <<: *first_card
    - <<: *left_card
    - <<: *top_card
    - <<: *right_card
  players:
    - <<: *first_player
    - <<: *left_player
    - <<: *top_player
    - <<: *right_player
5:
  top_margin: 40px
  cards:
    - <<: *first_card
    - <<: *bottom_left_card
    - <<: *top_left_card
      left: 190px
    - <<: *top_right_card
      left: 40px
    - <<: *bottom_right_card
  players:
    - <<: *first_player
    - <<: *bottom_left_player
    - <<: *top_left_player
      top: -50px
    - <<: *top_right_player
      top: -50px
    - <<: *bottom_right_player
